version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
      
volumes:
  postgres-data: